# This is a comment line
# Sample makefile for fraction class

main: main.cpp examplewindow.cpp examplewindow.h
	g++ -o main examplewindow.cpp main.cpp `pkg-config --cflags --libs gtkmm-3.0`

clean:
	rm *.o frac
