# This is a comment line
# Sample makefile for fraction class


main: main.cpp mainwindow.cpp mainwindow.h
	g++ -o main mainwindow.cpp main.cpp `pkg-config --cflags --libs gtkmm-3.0`

clean:
	rm *.o frac

